# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-deploy-argocd
  description: Deploy on Kubernetes with Helm/Helmfile and ArgoCD
  homepage: https://cloudposse.com/accelerate
  topics: ""

