name: 'Deploy ArgoCD'
description: 'Deploy on Kubernetes with ArgoCD'
author: hello@cloudposse.com
branding:
  icon: 'cpu'
  color: 'white'
inputs:
  cluster:
    description: Cluster name
    required: true
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  helmfile-path:
    description: The path where lives the helmfile.
    required: false
    default: deploy
  helmfile:
    description: Helmfile name
    required: false
    default: helmfile.yaml
  operation:
    description: Operation with helmfiles. (valid options - `deploy`, `destroy`)
    required: true
    default: deploy
  environment:
    description: Helmfile environment
    required: false
    default: preview
  gitref-sha:
    description: Git SHA
    required: false
    default: ''
  namespace:
    description: Kubernetes namespace
    required: true
  application:
    description: Application name
    required: true
  image:
    description: Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  debug:
    description: Debug mode
    default: 'false'
    required: false
  release_label_name:
    description: The name of the label used to describe the helm release
    default: "release"
    required: false
  github-pat:
    description: Github PAT to access argocd configuration repository
    required: true
outputs:
  webapp-url:
    description: "Web Application url"
    value: "https://example.com"
runs:
  using: "composite"
  steps:
    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1.0.1
      with:
        version: v4.28.1
        download-compressed: true
        force: true

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.2.0
      with:
        helmfile-version: v0.148.1
        helm-version: v3.10.2
        install-kubectl: false

    - id: destination
      uses: theowenyoung/git-url-parse@v1
      with:
        url: ${{ inputs.cluster }}

    - name: Checkout Argo Configuration
      uses: actions/checkout@v2
      with:
        repository: ${{ steps.destination.outputs.owner }}/${{ steps.destination.outputs.name }}
        ref: ${{ steps.destination.outputs.ref }}
        token: ${{ inputs.github-pat }}
        path: .destination

    - name: AWS Get caller identity
      uses: docker://segment/chamber:2.11.0
      with:
        args: --verbose export platform/default/${{ inputs.environment }} --format yaml --output-file ./platform.yaml

    - name: YQ Platform settings
      shell: bash
      run: |
        yq --exit-status --no-colors --inplace eval '{"platform": .}' ./platform.yaml

    - name: Helmfile render
      shell: bash
      run: |
        mkdir -p  .destination/${{ steps.destination.outputs.filepath }}
        helmfile --namespace ${{ inputs.namespace }} \
                --environment ${{ inputs.environment }} \
                --file ${{ inputs.helmfile-path}}/${{ inputs.helmfile }} \
                --state-values-file $(pwd)/platform.yaml template > \
          .destination/${{ steps.destination.outputs.filepath }}/${{ inputs.application }}.yaml

    - name: Commit files
      uses: actions-x/commit@v6
      with:
        email: bot@cloudposse.com
        name: GitHub Actions Autocommitter
        branch: main
        repository: https://github.com/cloudposse/argocd-deploy-non-prod-test
        files: ${{ steps.destination.outputs.filepath }}/${{ inputs.application }}.yaml
        token: ${{ inputs.github-pat }}
        force: true
        directory: .destination