name: 'Deploy ArgoCD'
description: 'Deploy on Kubernetes with ArgoCD'
author: hello@cloudposse.com
branding:
  icon: 'cpu'
  color: 'white'
inputs:
  cluster:
    description: Cluster name
    required: true
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  path:
    description: The path where lives the helmfile or helm chart.
    required: true
  toolchain:
    description: Toolchain ('helm', 'helmfile')
    required: false
    default: helmfile
  ssm-path:
    required: true
    description: SSM path to read environment secrets
  operation:
    description: Operation with helmfiles. (valid options - `deploy`, `destroy`)
    required: true
    default: deploy
  environment:
    description: Helmfile environment
    required: false
    default: preview
  repository:
    description: Application GitHub repository full name
    required: true
  ref:
    description: Git ref
    required: true
  gitref-sha:
    description: Git SHA (Depricated. Use `ref` instead)
    required: false
    default: ''
  namespace:
    description: Kubernetes namespace
    required: true
  application:
    description: Application name
    required: true
  image:
    description: Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  debug:
    description: Debug mode
    default: 'false'
    required: false
  values_file:
    description: Helm values file, this can be a single file or a comma separated list of files
    default: ""
    required: false
  release_label_name:
    description: The name of the label used to describe the helm release
    default: "release"
    required: false
  github-pat:
    description: Github PAT to access argocd configuration repository
    required: true
  synchronously:
    description: "Wait until ArgoCD successfully apply the changes"
    default: 'false'
  check-retry-count:
    description: 'Check retry count (for synchronously mode)'
    required: false
    default: "5"
  check-retry-interval:
    description: 'Check retry interval (in seconds) (for synchronously mode)'
    required: false
    default: "10"
  commit-retry-count:
    description: 'Commit retry count'
    required: false
    default: "4"
  commit-retry-interval:
    description: 'Commit retry interval (in seconds)'
    required: false
    default: "10"
  commit-timeout:
    description: 'Commit timeout (in seconds)'
    required: false
    default: "60"
  helm-dependency-build:
    description: 'Run helm dependency build, only for helm toolchain, `true` or `false`'
    required: false
    default: "false"
outputs:
  webapp-url:
    description: "Web Application url"
    value: ${{ steps.result.outputs.webapp_url }}
  sha:
    description: "Git commit SHA into argocd repo"
    value: ${{ steps.git.outputs.sha }}
runs:
  using: "composite"
  steps:
    - name: Setup yq
      uses: dcarbone/install-yq-action@v1.1.0
      with:
        version: v4.28.1
        download-compressed: true
        force: true

    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v1.2.0
      if: ${{ inputs.operation == 'deploy' }}
      with:
        helmfile-version: v0.148.1
        helm-version: v3.10.2
        install-kubectl: false

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install git-url-parse
      shell: bash
      run: npm install git-url-parse@14.0.0

    - name: Parse git URL for destination
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1, node 20
      id: destination
      with:
        script: |
          const GitUrlParse = require("git-url-parse");
          function run(url) {
            try { 
              console.log("url: %s", url)
              const urlObj = GitUrlParse(url);
              core.setOutput('result', JSON.stringify(urlObj));
              const keys = Object.keys(urlObj);
              keys.forEach(key=>{
                if(typeof urlObj[key] === 'string' || urlObj[key] === null){
                  core.setOutput(key, urlObj[key]);
                }
              })
            } 
            catch (error) {
              core.setFailed(error.message);
            }
          }
          run("${{ inputs.cluster }}")

    - id: destination_dir
      shell: bash
      run: |-
        echo "name=$(echo $RANDOM | md5sum | head -c 20)" >> $GITHUB_OUTPUT

    - name: Config
      id: config
      uses: cloudposse/github-action-yaml-config-query@0.1.3
      with:
        config: |-
          tmp: ./tmp/${{ steps.destination.outputs.filepath }}/${{ inputs.namespace }}/${{ inputs.application }}
          path: ${{ steps.destination.outputs.filepath }}/${{ inputs.namespace }}/${{ inputs.application }}

    - name: Checkout Argo Configuration
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.destination.outputs.owner }}/${{ steps.destination.outputs.name }}
        ref: ${{ steps.destination.outputs.ref }}
        token: ${{ inputs.github-pat }}
        path: ${{ steps.destination_dir.outputs.name }}

    - name: Setup chamber
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      env:
        version: v2.14.1
      run: |
        set -x
        os=$(uname -s | tr '[:upper:]' '[:lower:]')
        arch=$(uname -m | tr '[:upper:]' '[:lower:]')
        curl -LOs https://github.com/segmentio/chamber/releases/download/${version}/chamber-${version}-${os}-${arch}
        install chamber-${version}-${os}-${arch} /usr/local/bin/chamber

    - name: Read platform context
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      run: |
        chamber --verbose export ${{ inputs.ssm-path }}/${{ inputs.environment }} --format yaml --output-file ./platform.yaml

    - name: YQ Platform settings
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      run: |
        sudo chmod 777 ./platform.yaml 
        yq --exit-status --no-colors --inplace eval '{"platform": .}' ./platform.yaml

    - name: Read platform metadata
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      run: |
        chamber --verbose export ${{ inputs.ssm-path }}/_metadata --format yaml --output-file ./_metadata.yaml

    - name: YQ Platform settings
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      id: metadata
      run: |
        for output in $(yq --exit-status --no-colors eval-all '. | to_entries | map( .key + "=" + .value ) | join("\n")' ./_metadata.yaml); do
          echo "${output}" >> $GITHUB_OUTPUT ;
        done

    - name: Context
      if: ${{ inputs.operation == 'deploy' }}
      id: arguments
      uses: cloudposse/github-action-yaml-config-query@0.1.3
      with:
        query: .${{ steps.metadata.outputs.kube_version == '' }}
        config: |-
          true: 
            kube_version: ""
          false:
            kube_version: --kube-version=${{ steps.metadata.outputs.kube_version }}      


    - name: Ensure argocd repo structure
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      run: |
        mkdir -p ${{ steps.config.outputs.tmp }}/manifests

    - name: Helmfile render
      if: ${{ inputs.toolchain == 'helmfile' && inputs.operation == 'deploy' }}
      shell: bash
      run: |
        helmfile --namespace ${{ inputs.namespace }} \
          --environment ${{ inputs.environment }} \
          --file ${{ inputs.path}} \
          --state-values-file $(pwd)/platform.yaml \
          template \
          --args="${{ steps.arguments.outputs.kube_version }}" \
          > ${{ steps.config.outputs.tmp }}/manifests/resources.yaml
      env:
        IMAGE_NAME: ${{ inputs.image }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        
    - name: Build Helm Dependencies
      if: ${{ inputs.toolchain == 'helm' && inputs.operation == 'deploy' && inputs.helm-dependency-build == 'true'}}
      shell: bash
      run: |
        helm dependency build ${{ inputs.path }}
        
    - name: Helm raw render
      if: ${{ inputs.toolchain == 'helm' && inputs.operation == 'deploy' }}
      shell: bash
      run: |
        IFS=', ' read -r -a array <<< "${{ inputs.values_file }}"
        for element in ${array[@]}; do VALUES_STR+="--values $element "; done
        
        helm template ${{ inputs.application }} ${{ inputs.path }} \
          --set image.repository=${{ inputs.image }} \
          --set image.tag=${{ inputs.image-tag }} \
          --set environment=${{ inputs.environment }} \
          --create-namespace=true \
          --namespace ${{ inputs.namespace }} \
          --set ingress.default.hosts.example=test \
          --values $(pwd)/platform.yaml \
          ${VALUES_STR} \
          ${{ steps.arguments.outputs.kube_version }} \
        > ${{ steps.config.outputs.tmp }}/manifests/resources.yaml
      env:
        IMAGE_NAME: ${{ inputs.image }}
        IMAGE_TAG: ${{ inputs.image-tag }}

    - name: Get Webapp
      if: ${{ inputs.operation == 'deploy' }}
      id: result
      shell: bash
      run: |-
        WEBAPP_URL=$( \
          yq -N eval-all '[.metadata.annotations["outputs.platform.cloudposse.com/webapp-url"] | select(. != null)] | .[0]' \
            ${{ steps.config.outputs.tmp }}/manifests/resources.yaml \
        )
        echo "webapp_url=${WEBAPP_URL}" >> $GITHUB_OUTPUT

    - name: Deplicated Ref
      if: ${{ inputs.operation == 'deploy' }}
      id: ref
      uses: cloudposse/github-action-yaml-config-query@0.1.3
      with:
        query: .${{ inputs.gitref-sha == '' }}
        config: |-
          true: 
            value: ${{ inputs.ref }}
          false:
            value: ${{ inputs.gitref-sha }}      

    - name: Config render
      if: ${{ inputs.operation == 'deploy' }}
      uses: 1arp/create-a-file-action@0.2
      with:
        path: ${{ steps.config.outputs.tmp }}
        file: config.yaml
        content: |-
          app_repository: ${{ inputs.repository }}
          app_commit: ${{ steps.ref.outputs.value }}
          app_hostname: ${{ steps.result.outputs.webapp_url }}
          name: ${{ inputs.namespace }}.${{ inputs.application }}
          namespace: ${{ inputs.namespace }}
          manifests: ${{ steps.config.outputs.path }}/manifests

    - name: Push to Github
      uses: nick-fields/retry@v2
      id: git
      with:
        max_attempts: ${{ inputs.commit-retry-count }}
        timeout_seconds: ${{ inputs.commit-timeout }}
        retry_wait_seconds: ${{ inputs.commit-retry-interval }}
        shell: bash
        command: |-
          set -e
          
          git config --global user.email "bot@example.com"
          git config --global user.name "cloudpossebot"

          pushd ./${{ steps.destination_dir.outputs.name }}
          
          git reset --hard origin/${{ steps.destination.outputs.ref }}
          git pull --rebase
          
          popd
          
          case '${{ inputs.operation }}' in
        
            deploy)
              cp -r ./tmp/* ./${{ steps.destination_dir.outputs.name }}/
            ;;
          
            destroy)
              rm -rf ./${{ steps.destination_dir.outputs.name }}/${{ steps.config.outputs.path }}
            ;;
          
            *)
              echo "Operation should be `deploy` or `destroy`"
              exit 1;
            ;;
          esac          
          
          pushd ./${{ steps.destination_dir.outputs.name }}
          
          git add -A
          git status
          git diff-index --quiet HEAD || git commit -m "Deploy ${{ github.repository }} SHA ${{ github.sha }} RUN ${{ github.run_id }} ATEMPT ${{ github.run_attempt }}"
          git push origin ${{ steps.destination.outputs.ref }}

          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          
          popd

    - uses: cloudposse/github-action-wait-commit-status@0.2.0
      if: ${{ inputs.synchronously == 'true' && inputs.operation == 'deploy' }}
      with:
        repository: ${{ inputs.repository }}
        sha: ${{ inputs.ref }}
        status: "continuous-delivery/${{ inputs.namespace }}.${{ inputs.application }}"
        expected_state: "success"
        token: ${{ inputs.github-pat }}
        check-retry-count: ${{ inputs.check-retry-count }}
        check-retry-interval: ${{ inputs.check-retry-interval }}      
